sudo: required

language: node_js

node_js:
  - '6'

addons:
  ssh_known_hosts: servers.andrewmacheret.com

env:
  global:
    # DOCKER_USERNAME and DOCKER_PASSWORD
    - secure: "tellH+HGhgMuBa2CSrlkUh/LoK4sga6NWJ1xtAPogC3LQB6oD/ki08/sDs3lfM7ZIEnwMs7vB0ntisWJ3Fm3MTpkc3s/swRo42YVuw7G40phbrEy4IcYKXHWg8pUMK7cfbbGQAU9Qd+3Htk+4j+9I+eaiPHQO4i3iuN18ZNeoiNM2FZ+bjTtl8LSFjqnS8w+TmEWh/Li0CGiJgSnJKtHiRURMUxabCKawUibdhIyyzGchZFAEir40kXIFiWYhmVATyjwIGAn847nPgG5WrcGeiN3sJhy+0eMkMBksJcE/p56eP0t44z7Qe1eAfxr9i50uLiIQUil8fcSq9Adl5tQDx1359FdNPlL+m2D401q0i/hquCiIwCh9JMVd5FC0qmWT47n3QTZ2kaktXj/EPHUWrdmYCst7QL6L2VaTLVhVop85Z8wcHMUUlYM1GgIe1GqS7DWly18gEy81Hwld+JlpSY023w/IZxbxr0ohRnfOVXs1Cyx/WQXbHOkPmZ5X3H2SVjKZM4RkMRHQ0quaMlCXegLxnaAq8gLRSBYGES9TXEGzFLecgcbwqJPVkMdrccPH9hTeZq5u9o6dxG/uKkgaPWZkR4rI/3am048465YSbjTkk4zHwlRYuNNyodU+p4vbOmQtLMF4t3X6n8O5tPHXgHHv1gz7R0gMQJi36obw74="
    - secure: "Wwj/avlhgUzZrgMUW3qrLQxFHQt/jd5EKoWN6x/RRAgQXOfRZc9xkcdL/EkwL2fshamJ33NVNQsZouSW7slDNM2Bov5Yeta4ElFm0bf/TnP/3vutS6BgTqhGNi8ez2tNRJSqUqgNGZA7GiCnpfPtjn1b6fHnGXtu7jVMf1A/CYLhpUW6xCSwiwJ4ubHPuyvQ4iOs4bZLwoOTKGmM1yV/vffQUgEou9HqDn6/sXxD4oSgS2/EFceqmjizBKouqCazJmA0EtcaWwteVdOzll/lTZ18obyIAJwCXi6lvs8sxP8AOZStxQOiNzF+P2qDGcwbvyfXRTCNtHE5wWcjyNVVI77BbU7zsl0a5/r/S2ZBRH51e3k+NJDQxjl/a3KYTGWtI30Ywj8J03eD30sS5R9eSEzbzcPoJQUWKuIXd2gAnmLlCnZw3yIVjLTgbTPNbzuxTKsDqhcRho4/3scF6JGRpUaq9TuV+ZIonx2HYZaMFSarD0bzJ8w1+pO3HDMFacrpMDX0Bu/wrMkq4XtHAqj9YqkNGpW4mx1fwgKgZ0p8nFMFPnX7CeMycZYGVW4LkE+p414d8Q7fTECDA5CUxdwo9+TNRIFGBe4hckHbVSh4mQcyRORBetr8EzLRbLV8tISxvLyqLkgkA0oSBwcQnugrseyCT+s2plzN81YgvkZZ0ME="
    - SERVICE_NAME='chess'
    - CONTAINER_NAME='chess-server'
    - VERSION=1.0
    - TEST_PORT='9999'
    - TEST_FEN='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'
    - TEST_DEPTH=15

services:
  - docker

install:
  # install dependencies
  - set -e
  - cd app && npm install && cd ..

script:
  # build and test
  - set -e
  - docker build -t "${DOCKER_USERNAME}/${CONTAINER_NAME}":latest .
  - docker run -d --name "${CONTAINER_NAME}" -p "${TEST_PORT}":80 "${DOCKER_USERNAME}/${CONTAINER_NAME}"
  - sleep 1

  - docker exec -it "${CONTAINER_NAME}" ./move.sh "${TEST_FEN}"
  - docker exec -it "${CONTAINER_NAME}" ./move.sh "${TEST_FEN}" "${TEST_DEPTH}"
  - curl "http://localhost:${TEST_PORT}/"
  - curl "http://localhost:${TEST_PORT}/moves"
  - curl "http://localhost:${TEST_PORT}/moves" --data-urlencode "fen=${TEST_FEN}"
  - curl "http://localhost:${TEST_PORT}/moves" --data-urlencode "fen=${TEST_FEN}" --data-urlencode "depth=${TEST_DEPTH}"

  - docker rm -f "${CONTAINER_NAME}"

after_success:
  # push to docker hub
  - set -e
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker tag "${DOCKER_USERNAME}/${CONTAINER_NAME}":latest "${DOCKER_USERNAME}/${CONTAINER_NAME}":"${VERSION}"
  - docker push "${DOCKER_USERNAME}/${CONTAINER_NAME}":latest
  - docker push "${DOCKER_USERNAME}/${CONTAINER_NAME}":"${VERSION}"
  # ssh deploy
  - openssl aes-256-cbc -K $encrypted_4783bc65e00d_key -iv $encrypted_4783bc65e00d_iv -in id_rsa_a1-server.enc -out "${TRAVIS_BUILD_DIR}/id_rsa_a1-server" -d
  - eval "$(ssh-agent -s)"
  - chmod 600 "${TRAVIS_BUILD_DIR}/id_rsa_a1-server"
  - ssh-add "${TRAVIS_BUILD_DIR}/id_rsa_a1-server"
  - ssh core@servers.andrewmacheret.com "~/servers/a1-servers/restart-service.sh ${SERVICE_NAME}"
